NetCore.Web/Areas/Tool/Controllers/ExcelController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NetCore.Common.Helpers;
using NetCore.Common.Models;
using NetCore.Web.Common.CustomAttribute;
using NetCore.Web.Common.Helpers;
using NPOI.SS.UserModel;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace NetCore.Web.Areas.Tool.Controllers
{
    public class ExcelController : BaseController
    {
        [MenuInfo(Title = "Excel操作", Sort = 1)]
        public IActionResult Index()
        {
            return View();
        }

        #region Npoi

        /// <summary>
        /// 导出模板
        /// </summary>
        /// <returns></returns>
        public IActionResult ExportNpoi()
        {
            try
            {
                NpoiHepler excelHepler = new NpoiHepler();
                int rowIndex = 0;
                int colIndex = 0;

                excelHepler.AddCell(rowIndex, colIndex++, "1位小数", NpoiStyleType.Title);
                excelHepler.AddCell(rowIndex, colIndex++, "日期时间", NpoiStyleType.Title);
                excelHepler.AddCell(rowIndex, colIndex++, "下拉框", NpoiStyleType.Title);
                excelHepler.AddCell(rowIndex, colIndex++, "合并2*2单元格", NpoiStyleType.Title, 1, 1);

                rowIndex++;
                colIndex = 0;
                excelHepler.AddCell(rowIndex, colIndex++, 100, NpoiStyleType.OneDecimalPlaces);
                excelHepler.AddCell(rowIndex, colIndex++, DateTime.Now, NpoiStyleType.DateTime);
                excelHepler.AddSelectCol(rowIndex, colIndex++, new string[] { "下拉框值1", "下拉框值2" });

                var fileDownloadName = $"示例.xlsx";
                return File(excelHepler.GetByte(), excelHepler.ContentType, fileDownloadName);
            }
            catch (Exception ex)
            {
                Response.ContentType = "text/plain;charset=utf-8";
                Response.WriteAsync("导出失败，请联系管理员，错误描述：" + ex.Message);
                return null;
            }
        }

        /// <summary>
        /// 上传
        /// </summary>
        /// <param name="file"></param>
        /// <returns></returns>
        public IActionResult UploadNpoi(IFormFile file)
        {
            JsonResultModel result = new JsonResultModel();
            try
            {
                #region 验证文件格式

                if (Request.Form.Files.Count == 0)
                {
                    result.IsOk = false;
                    result.Msg = "请选择上传文件";
                    return Json(result);
                }
                string fileExt = System.IO.Path.GetExtension(file.FileName).ToLower();
                if (fileExt != ".xlsx")
                {
                    result.IsOk = false;
                    result.Msg = "上传的文件类型必须为.xlsx类型";
                    return Json(result);
                }

                #endregion 验证文件格式

                #region 获取文件数据

                IWorkbook wk = null;
                if (fileExt == ".xls")
                {
                    //把xls文件中的数据写入wk中
                    wk = new NPOI.HSSF.UserModel.HSSFWorkbook(file.OpenReadStream());
                }
                else
                {
                    //把xlsx文件中的数据写入wk中
                    wk = new NPOI.XSSF.UserModel.XSSFWorkbook(file.OpenReadStream());
                }
                //读取当前表数据
                ISheet sheet = wk.GetSheetAt(0);
                if (sheet.LastRowNum < 1)
                {
                    result.IsOk = false;
                    result.Msg = "上传的Excel无内容";
                    return Json(result);
                }
                List<List<string>> dataList = new List<List<string>>();
                for (int rowNum = 0; rowNum < sheet.LastRowNum; rowNum++)
                {
                    var row = sheet.GetRow(rowNum);
                    if (row != null)
                    {
                        List<string> rowList = new List<string>();
                        for (int colNum = 0; colNum < row.LastCellNum; colNum++)
                        {
                            var cell = row.GetCell(colNum);
                            rowList.Add(NpoiHepler.GetCellValue(cell));
                        }
                        dataList.Add(rowList);
                    }
                }

                #endregion 获取文件数据

                result.Data = dataList;
                return Json(result);
            }
            catch (Exception ex)
            {
                result.IsOk = false;
                result.Msg = "导入出错:" + ex.Message;
            }

            return Json(result);
        }

        #endregion Npoi

        #region EPPlus

        /// <summary>
        /// 导出模板
        /// </summary>
        /// <returns></returns>
        public IActionResult ExportEPPlus()
        {
            try
            {
                //指定EPPlus使用非商业证书,否则报错
                ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
                using (ExcelPackage package = new ExcelPackage())
                {
                    ExcelWorksheet workSheet = package.Workbook.Worksheets.Add("Sheet1");

                    #region 插入数据，坐标从1开始

                    var list = RandomUserHelper.GetList().Take(10).ToList();
                    int rowIndex = 1;
                    for (int n = 0; n < list.Count; n++)
                    {
                        var data = list[n];
                        int colIndex = 1;
                        AddCells(workSheet, rowIndex, colIndex, data.Id);
                        colIndex++;
                        AddCells(workSheet, rowIndex, colIndex, data.Name);
                        colIndex++;
                        AddCells(workSheet, rowIndex, colIndex, data.Birthday);
                        colIndex++;
                        AddCells(workSheet, rowIndex, colIndex, data.Age);
                        colIndex++;
                        AddCells(workSheet, rowIndex, colIndex, data.Sex);
                        colIndex++;
                        AddCells(workSheet, rowIndex, colIndex, data.Height);

                        rowIndex++;
                    }

                    AddCells(workSheet, rowIndex, 1, "合并单元格", true, 2, 2);

                    #endregion 插入数据，坐标从1开始

                    #region 列宽度设置

                    //自动宽度，填完内容后调用
                    workSheet.Cells[workSheet.Dimension.Address].AutoFitColumns();

                    #endregion 列宽度设置

                    return File(package.GetAsByteArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Epplus模板.xlsx");
                }
            }
            catch (Exception ex)
            {
                Response.ContentType = "text/plain;charset=utf-8";
                Response.WriteAsync("导出失败，请联系管理员，错误描述：" + ex.Message);
                return null;
            }
        }

        /// <summary>
        /// 插入单元格数据
        /// </summary>
        /// <param name="workSheet">ExcelWorksheet 对象</param>
        /// <param name="rowIndex">行</param>
        /// <param name="colIndex">列</param>
        /// <param name="value">值</param>
        /// <param name="border">是否显示边框</param>
        /// <param name="mergeColumns">合并的几列</param>
        /// <param name="mergeRow">合并的几行</param>
        public void AddCells(ExcelWorksheet workSheet, int rowIndex, int colIndex, object value, bool border = true, int mergeColumns = 0, int mergeRow = 0)
        {
            switch (value.GetType().ToString())
            {
                case "System.String"://字符串类型
                    workSheet.Cells[rowIndex, colIndex].Value = value;
                    break;

                case "System.DateTime"://日期类型
                    workSheet.Cells[rowIndex, colIndex].Style.Numberformat.Format = "yyyy-mm-d h:mm:ss";
                    workSheet.Cells[rowIndex, colIndex].Value = value;
                    break;

                case "System.Boolean"://布尔型
                    workSheet.Cells[rowIndex, colIndex].Value = (bool)value ? "是" : "否";
                    break;

                case "System.Int16"://整型
                case "System.Int32":
                case "System.Int64":
                case "System.Byte":
                    workSheet.Cells[rowIndex, colIndex].Style.Numberformat.Format = "#,##0";
                    workSheet.Cells[rowIndex, colIndex].Value = value;
                    break;

                case "System.Decimal"://浮点型
                case "System.Double":
                    workSheet.Cells[rowIndex, colIndex].Style.Numberformat.Format = "#,##0.00";
                    workSheet.Cells[rowIndex, colIndex].Value = value;
                    break;

                case "System.DBNull"://空值处理
                    workSheet.Cells[rowIndex, colIndex].Value = "";
                    break;

                default:
                    workSheet.Cells[rowIndex, colIndex].Value = "";
                    break;
            }

            //合并单元格
            if (mergeColumns > 0 || mergeRow > 0)
            {
                workSheet.Cells[rowIndex, colIndex, rowIndex + mergeRow, colIndex + mergeColumns].Merge = true;
                if (border)
                {
                    workSheet.Cells[rowIndex, colIndex, rowIndex + mergeRow, colIndex + mergeColumns].Style.Border.Top.Style = ExcelBorderStyle.Thin;
                    workSheet.Cells[rowIndex, colIndex, rowIndex + mergeRow, colIndex + mergeColumns].Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
                    workSheet.Cells[rowIndex, colIndex, rowIndex + mergeRow, colIndex + mergeColumns].Style.Border.Left.Style = ExcelBorderStyle.Thin;
                    workSheet.Cells[rowIndex, colIndex, rowIndex + mergeRow, colIndex + mergeColumns].Style.Border.Right.Style = ExcelBorderStyle.Thin;
                }
            }
            else if (border)
            {

NetCore.Web/Areas/Tool/Views/Excel/Index.cshtml
@{
    ViewData["Title"] = "Excel操作";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <a href="https://github.com/nissl-lab/npoi/wiki/Getting-Started-with-NPOI" target="_blank">Npoi</a>
        </div>
        <div class="card-body">
            <form class="form-inline">
                <input class="form-control" id="editFile" type="file" style="display:none;" onchange="$('#editFileText').val($(this).val());" />
                <input class="form-control mb-2 mr-sm-2" id="editFileText" type="text" readonly style="width:300px;" />
                <button type="button" class="btn btn-info mb-2 mr-sm-2" onclick="$('#editFile').click();">选择文件</button>
                <button type="button" class="btn btn-primary mb-2 mr-sm-2" onclick="uploadExcel();">上传</button>
                <a class="mb-2 mr-sm-2" asp-area="Tool" asp-controller="Excel" asp-action="ExportNpoi" target="_blank">模板下载</a>
            </form>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <a href="https://epplussoftware.com/" target="_blank">EPPlus</a>
        </div>
        <div class="card-body">
            <form class="form-inline">
                <input class="form-control" id="editFile2" type="file" style="display:none;" onchange="$('#editFileText2').val($(this).val());" />
                <input class="form-control mb-2 mr-sm-2" id="editFileText2" type="text" readonly style="width:300px;" />
                <button type="button" class="btn btn-info mb-2 mr-sm-2" onclick="$('#editFile2').click();">选择文件</button>
                <button type="button" class="btn btn-primary mb-2 mr-sm-2" onclick="uploadExcel2();">上传</button>
                <a class="mb-2 mr-sm-2" asp-area="Tool" asp-controller="Excel" asp-action="ExportEPPlus" target="_blank">模板下载</a>
            </form>
        </div>
    </div>
</div>
@section Scripts{
    <script type="text/javascript">
        //上传
        function uploadExcel() {
            if (!$("#editFile").val()) {
                ShowMessage("请选择文件!");
                return false;
            }

            var formData = new FormData();
            formData.append("file", $("#editFile")[0].files[0]);
            ShowProcess();
            $.ajax({
                url: "@Url.Action("UploadNpoi")",
                type: 'POST',
                data: formData,
                dataType: "json",
                processData: false,
                contentType: false,
                async: false,
                success: function (rsp) {
                    if (rsp.isOk) {
                        ShowMessage("控制台查看！");
                        console.table(rsp.data);
                    } else {
                        ShowMessage(rsp.msg);
                    }
                    HideProcess();
                },
                error: function (data) {
                    ShowMessage("文件上传失败,请重试");
                    HideProcess();
                }
            });

            return false;//防止跳转
        }

        //上传
        function uploadExcel2() {
            if (!$("#editFile").val()) {
                ShowMessage("请选择文件!");
                return false;
            }

            var formData = new FormData();
            formData.append("file", $("#editFile")[0].files[0]);
            ShowProcess();
            $.ajax({
                url: "@Url.Action("UploadNpoi")",
                type: 'POST',
                data: formData,
                dataType: "json",
                processData: false,
                contentType: false,
                async: false,
                success: function (rsp) {
                    if (rsp.isOk) {
                        ShowMessage("控制台查看！");
                        console.table(rsp.data);
                    } else {
                        ShowMessage(rsp.msg);
                    }
                    HideProcess();
                },
                error: function (data) {
                    ShowMessage("文件上传失败,请重试");
                    HideProcess();
                }
            });

            return false;//防止跳转
        }
    </script>
}