NetCore.Web/Areas/JSPlugin/Controllers/UploadController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using NetCore.Web.Common.CustomAttribute;
using NetCore.Web.Areas.JSPlugin.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace NetCore.Web.Areas.JSPlugin.Controllers {
    public class UploadController : BaseController {

        IWebHostEnvironment _webHostEnvironment;
        public UploadController(IWebHostEnvironment webHostEnvironment) {
            _webHostEnvironment = webHostEnvironment;
        }


        [MenuInfo(Title = "文件上传", Sort = 1)]
        public IActionResult Index() {
            return View();
        }

        public IActionResult UploadFile(List<IFormFile> files) {

            //asp.net使用Server.MapPath("~/")
            string content_path = _webHostEnvironment.ContentRootPath;//E:\代码\NetCore.Demo\NetCore.Web
            string web_path = _webHostEnvironment.WebRootPath;//E:\代码\NetCore.Demo\NetCore.Web\wwwroot

            if (files?.Count > 0) {
                return Json(files[0].FileName);
            }
            return Json("无文件");
        }
    }
}

NetCore.Web/Areas/JSPlugin/Views/Upload/Index.cshtml
@{
    ViewData["Title"] = "文件上传";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles{
    <style type="text/css">
        form p {
            margin: 5px;
        }
    </style>
}
<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <a href="https://www.jianshu.com/p/5147e36cf19c" target="_blank">Form表单上传文件，会刷新页面</a>
        </div>
        <div class="card-body" style="padding:0;">
            <form method="POST" enctype="multipart/form-data" action="@Url.Action("UploadFile","Upload",new { area ="JSPlugin" })">
                <p>
                    <input type="file" name="files" value="请选择文件" />
                </p>
                <p>
                    <button type="submit">提交</button>
                </p>
            </form>
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            <a href="https://www.jianshu.com/p/5147e36cf19c" target="_blank">ajax上传文件</a>
        </div>
        <div class="card-body" style="padding:0;">
            <form>
                <p>
                    <input id="ajaxFile" type="file" style="display:none;" onchange="fileChange(this)" />
                    <input id="fileName" type="text" readonly />
                    <button type="button" onclick="selectFile()">选择文件</button>
                </p>
                <p>
                    <button type="button" onclick="ajaxUpload()">提交</button>
                </p>
            </form>
        </div>
    </div>
</div>
@section Scripts{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript">
        function selectFile() {
            $("#ajaxFile").click();
        }

        function fileChange(e) {
            var file = $(e).val();
            if (file != '') {
                var pos = file.lastIndexOf("\\");
                file = file.substring(pos + 1);
            }
            $("#fileName").val(file);
        }

        function ajaxUpload() {
            if (!$("#ajaxFile").val()) {
                alert("请选择文件!");
                return false;
            }
            var fileext = '';
            var i = $("#ajaxFile").val().lastIndexOf(".");
            if (i > -1) {
                fileext = $("#ajaxFile").val().substring(i).toLowerCase();
            }
            if (fileext != '.jpg' && fileext != '.png') {
                alert("上传文件的格式需为.jpg或者.png!");
                return false;
            }
            var file = $("#ajaxFile")[0].files[0];
            var fileSize = file.size;//单位：b
            if (fileSize > (2 * 1024 * 1024)) {
                alert("上传文件的大小限制在2M以内");
                return false;
            }

            //利用formData对象ajax上传，IE10支持
            var formData = new FormData();
            formData.append("files", $("#ajaxFile")[0].files[0]);
            $.ajax({
                url: "@Url.Action("UploadFile", "Upload",new { area ="JSPlugin" })",
                type: 'POST',
                data: formData,
                processData: false,
                contentType: false,
                async: false,
                success: function (data) {
                    alert(data)
                }
            });
        }

    </script>
}